CREATE DATABASE DB_F4ALL;

CREATE TABLE USERS (
    US_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    US_NAME VARCHAR(255) NOT NULL,
    US_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    US_PASSW VARCHAR(40) NOT NULL,
    US_LINKEDIN VARCHAR(255),
    US_GITHUB VARCHAR(255),
    US_BIRTH DATE NOT NULL,
    US_DESCRIPTION VARCHAR(10000),
    US_IMAGE VARCHAR(255)
);

CREATE TABLE TOPICS (
    TOP_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TOP_SUBJECT VARCHAR(100) NOT NULL,
    TOP_TITLE VARCHAR(100) NOT NULL,
    TOP_DATE DATETIME NOT NULL,
    TOP_US_ID INT NOT NULL,
    CONSTRAINT FK_TOP FOREIGN KEY (TOP_US_ID) REFERENCES USERS (US_ID)
);

CREATE TABLE COMMENTS (
    COM_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    COM_CONTENT VARCHAR(10000) NOT NULL,
    COM_DATE DATETIME NOT NULL,    
    COM_IMAGE VARCHAR(255),
    COM_TOP_ID INT NOT NULL,
    CONSTRAINT FK_COM FOREIGN KEY (COM_TOP_ID) REFERENCES TOPICS (TOP_ID)
);

CREATE TABLE T_UP_DOWN_VOTE (
    TUD_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE C_UP_DOWN_VOTE (
    CUD_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE US_COM (
    FK_US_ID INT NOT NULL,
    FK_COM_ID INT NOT NULL,
    CONSTRAINT FK_US_COM_US FOREIGN KEY (FK_US_ID) REFERENCES USERS (US_ID),
    CONSTRAINT FK_US_COM_COM FOREIGN KEY (FK_COM_ID) REFERENCES COMMENTS (COM_ID)    
);

CREATE TABLE US_TUD (
    FK_US_ID INT NOT NULL,
    FK_TUD_ID INT NOT NULL,
    CONSTRAINT FK_US_TUD_US FOREIGN KEY (FK_US_ID) REFERENCES USERS (US_ID),
    CONSTRAINT FK_US_TUD_CUD FOREIGN KEY (FK_TUD_ID) REFERENCES T_UP_DOWN_VOTE (TUD_ID)    
);

CREATE TABLE US_CUD (
    FK_US_ID INT NOT NULL,
    FK_CUD_ID INT NOT NULL,
    CONSTRAINT FK_US_CUD_US FOREIGN KEY (FK_US_ID) REFERENCES USERS (US_ID),
    CONSTRAINT FK_US_CUD_CUD FOREIGN KEY (FK_CUD_ID) REFERENCES C_UP_DOWN_VOTE (CUD_ID)    
);    

CREATE TABLE TOP_TUD (
    FK_TOP_ID INT NOT NULL,
    FK_TUD_ID INT NOT NULL,
    CONSTRAINT FK_TOP_TUD_TOP FOREIGN KEY (FK_TOP_ID) REFERENCES TOPICS (TOP_ID),
    CONSTRAINT FK_TOP_TUD_TUD FOREIGN KEY (FK_TUD_ID) REFERENCES T_UP_DOWN_VOTE (TUD_ID)    
);

CREATE TABLE COM_CUD (
    FK_COM_ID INT NOT NULL,
    FK_CUD_ID INT NOT NULL,
    CONSTRAINT FK_COM_CUD_COM FOREIGN KEY (FK_COM_ID) REFERENCES COMMENTS (COM_ID),
    CONSTRAINT FK_COM_CUD_CUD FOREIGN KEY (FK_CUD_ID) REFERENCES C_UP_DOWN_VOTE (CUD_ID)    
);
