CREATE DATABASE DB_F4ALL;

CREATE TABLE USERS (
    US_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    US_NAME VARCHAR(255) NOT NULL,
    US_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    US_PASSW VARCHAR(16) NOT NULL,
    US_LINKEDIN VARCHAR(255),
    US_GITHUB VARCHAR(255),
    US_BIRTH DATE,
    US_DESCRIPTION VARCHAR(10000)
);

CREATE TABLE TOPICS (
    TOP_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TOP_SUBJECT VARCHAR(100) NOT NULL,
    TOP_TITLE VARCHAR(100) NOT NULL,
    TOP_CONTENT VARCHAR(10000) NOT NULL,
    TOP_DATE DATETIME NOT NULL,
    TOP_US_ID INT NOT NULL,
    CONSTRAINT FK_TOP FOREIGN KEY (TOP_US_ID) REFERENCES USERS (US_ID)
);

CREATE TABLE COMMENTS (
    COM_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    COM_CONTENT VARCHAR(10000) NOT NULL,
    COM_DATE DATETIME NOT NULL,
    COM_TOP_ID INT NOT NULL,
    CONSTRAINT FK_COM FOREIGN KEY (COM_TOP_ID) REFERENCES TOPICS (TOP_ID)
);

CREATE TABLE LIKES_DISLIKES (
    LD_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE US_LD (
    FK_US_ID INT,
    FK_LD_ID INT,
    CONSTRAINT FK_US_LD_US FOREIGN KEY (FK_US_ID) REFERENCES USERS (US_ID),
    CONSTRAINT FK_US_LD_LD FOREIGN KEY (FK_LD_ID) REFERENCES LIKES_DISLIKES (LD_ID)
);

CREATE TABLE TOP_LD (
    FK_TOP_ID INT,
    FK_LD_ID INT,
    CONSTRAINT FK_TOP_LD_TOP FOREIGN KEY (FK_TOP_ID) REFERENCES TOPICS (TOP_ID),
    CONSTRAINT FK_TOP_LD_LD FOREIGN KEY (FK_LD_ID) REFERENCES LIKES_DISLIKES (LD_ID)
);

CREATE TABLE US_COM (
    FK_COM_ID INT,
    FK_US_ID INT,
    CONSTRAINT FK_US_COM_COM FOREIGN KEY (FK_COM_ID) REFERENCES COMMENTS (COM_ID),
    CONSTRAINT FK_US_COM_US FOREIGN KEY (FK_US_ID) REFERENCES USERS (US_ID)
);

CREATE TABLE LD_COM (
    FK_LD_ID INT,
    FK_COM_ID INT,
    CONSTRAINT FK_LD_COM_LD FOREIGN KEY (FK_LD_ID) REFERENCES LIKES_DISLIKES (LD_ID),
    CONSTRAINT FK_LD_COM_COM FOREIGN KEY (FK_COM_ID) REFERENCES COMMENTS (COM_ID)
);